name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' 

      - name: Publish App
        run: |
          dotnet publish NotepadeGrid/NotepadeGrid.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Zip release
        run: Compress-Archive -Path ./publish/* -DestinationPath NotepadeGrid.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: NotepadeGrid.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
